from sqlalchemy import String, Integer, Column, ForeignKey
from app.repositories.DataBase import DBase
from sqlalchemy.orm import relationship

"""class ObjTable_Model(DBase):
    __tablename__ = "Objetos"

    name = Column(String, unique=True, prymary_key=True)
    type = Column(String)

class Mark_Model(DBase):
    __tablename__ = "Marcas"

    name = Column(String,unique=True,primary_key=True)
    type = Column(String)

class ObjtMark_Model(DBase):
    __tablename__ = "Obj-Marca"
    
    id = Column(Integrer,primary_key=True,index=True)
    markname = Column(String,foreign_key=True)
    objname = Column(String,foreign_key=True)
"""    
class Prdct_Key_Model(DBase):
    __tablename__ = "Product_Keys"

    id = Column(Integer,primary_key=True,index=True)
    key1 = Column(String)
    key2 = Column(String)
    key3 = Column(String)
    key4 = Column(String)
    key5 = Column(String)
    key6 = Column(String)
    key7 = Column(String)
    key8 = Column(String)
    key9 = Column(String)
    key10 = Column(String)
    key11 = Column(String)
    key12 = Column(String)
    key13 = Column(String)
    key14 = Column(String)
    key15 = Column(String)
    key16 = Column(String)
    key17 = Column(String)
    key18 = Column(String)
    key19 = Column(String)
    key20 = Column(String)
    key21 = Column(String)
    key22 = Column(String)
    key23 = Column(String)
    key24 = Column(String)
    key25 = Column(String)
    key26 = Column(String)
    key27 = Column(String)
    key28 = Column(String)
    key29 = Column(String)
    key30 = Column(String)
    key31 = Column(String)
    key32 = Column(String)
    key33 = Column(String)
    key34 = Column(String)
    key35 = Column(String)
    key36 = Column(String)
    key37 = Column(String)
    key38 = Column(String)
    key39 = Column(String)
    key40 = Column(String)
    key41 = Column(String)
    key42 = Column(String)
    key43 = Column(String)
    key44 = Column(String)
    key45 = Column(String)
    key46 = Column(String)
    key47 = Column(String)
    key48 = Column(String)
    key49 = Column(String)
    key50 = Column(String)
    key51 = Column(String)
    key52 = Column(String)
    key53 = Column(String)
    key54 = Column(String)
    key55 = Column(String)
    key56 = Column(String)
    key57 = Column(String)
    key58 = Column(String)
    key59 = Column(String)
    key60 = Column(String)

    ky = relationship("Product_Values",back_populates="val",uselist=False)
    
class Prdct_Value_Model(DBase):
    __tablename__ = "Product_Values"

    id = Column(Integer,primary_key=True,index=True)
    num = Column(Integer, ForeignKey("Product_Keys.id"))
    key1 = Column(String)
    key2 = Column(String)
    key3 = Column(String)
    key4 = Column(String)
    key5 = Column(String)
    key6 = Column(String)
    key7 = Column(String)
    key8 = Column(String)
    key9 = Column(String)
    key10 = Column(String)
    key11 = Column(String)
    key12 = Column(String)
    key13 = Column(String)
    key14 = Column(String)
    key15 = Column(String)
    key16 = Column(String)
    key17 = Column(String)
    key18 = Column(String)
    key19 = Column(String)
    key20 = Column(String)
    key21 = Column(String)
    key22 = Column(String)
    key23 = Column(String)
    key24 = Column(String)
    key25 = Column(String)
    key26 = Column(String)
    key27 = Column(String)
    key28 = Column(String)
    key29 = Column(String)
    key30 = Column(String)
    key31 = Column(String)
    key32 = Column(String)
    key33 = Column(String)
    key34 = Column(String)
    key35 = Column(String)
    key36 = Column(String)
    key37 = Column(String)
    key38 = Column(String)
    key39 = Column(String)
    key40 = Column(String)
    key41 = Column(String)
    key42 = Column(String)
    key43 = Column(String)
    key44 = Column(String)
    key45 = Column(String)
    key46 = Column(String)
    key47 = Column(String)
    key48 = Column(String)
    key49 = Column(String)
    key50 = Column(String)
    key51 = Column(String)
    key52 = Column(String)
    key53 = Column(String)
    key54 = Column(String)
    key55 = Column(String)
    key56 = Column(String)
    key57 = Column(String)
    key58 = Column(String)
    key59 = Column(String)
    key60 = Column(String)

    val = relationship("Product_Keys", back_populates="ky")





